package entities;
// Generated 26 Nov, 2016 2:48:47 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RegDet generated by hbm2java
 */
@Entity
@Table(name = "RegDet", catalog = "ChatSys")
public class RegDet implements java.io.Serializable {

	private RegDetId id;
	private UserD userD;

	public RegDet() {
	}

	public RegDet(RegDetId id, UserD userD) {
		this.id = id;
		this.userD = userD;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "li", column = @Column(name = "LI", nullable = false)),
			@AttributeOverride(name = "lname", column = @Column(name = "LName")),
			@AttributeOverride(name = "lpass", column = @Column(name = "LPass")),
			@AttributeOverride(name = "fullName", column = @Column(name = "FullName")),
			@AttributeOverride(name = "phone", column = @Column(name = "Phone", length = 12)),
			@AttributeOverride(name = "email", column = @Column(name = "Email", length = 50)) })
	public RegDetId getId() {
		return this.id;
	}

	public void setId(RegDetId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LI", nullable = false, insertable = false, updatable = false)
	public UserD getUserD() {
		return this.userD;
	}

	public void setUserD(UserD userD) {
		this.userD = userD;
	}

}
