package entities;
// Generated 26 Nov, 2016 2:48:47 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegDetId generated by hbm2java
 */
@Embeddable
public class RegDetId implements java.io.Serializable {

	private int li;
	private Serializable lname;
	private Serializable lpass;
	private String fullName;
	private String phone;
	private String email;

	public RegDetId() {
	}

	public RegDetId(int li) {
		this.li = li;
	}

	public RegDetId(int li, Serializable lname, Serializable lpass, String fullName, String phone, String email) {
		this.li = li;
		this.lname = lname;
		this.lpass = lpass;
		this.fullName = fullName;
		this.phone = phone;
		this.email = email;
	}

	@Column(name = "LI", nullable = false)
	public int getLi() {
		return this.li;
	}

	public void setLi(int li) {
		this.li = li;
	}

	@Column(name = "LName")
	public Serializable getLname() {
		return this.lname;
	}

	public void setLname(Serializable lname) {
		this.lname = lname;
	}

	@Column(name = "LPass")
	public Serializable getLpass() {
		return this.lpass;
	}

	public void setLpass(Serializable lpass) {
		this.lpass = lpass;
	}

	@Column(name = "FullName")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "Phone", length = 12)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegDetId))
			return false;
		RegDetId castOther = (RegDetId) other;

		return (this.getLi() == castOther.getLi())
				&& ((this.getLname() == castOther.getLname()) || (this.getLname() != null
						&& castOther.getLname() != null && this.getLname().equals(castOther.getLname())))
				&& ((this.getLpass() == castOther.getLpass()) || (this.getLpass() != null
						&& castOther.getLpass() != null && this.getLpass().equals(castOther.getLpass())))
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLi();
		result = 37 * result + (getLname() == null ? 0 : this.getLname().hashCode());
		result = 37 * result + (getLpass() == null ? 0 : this.getLpass().hashCode());
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		return result;
	}

}
