package entities;
// Generated 26 Nov, 2016 2:48:47 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserContact generated by hbm2java
 */
@Entity
@Table(name = "UserContact", catalog = "ChatSys")
public class UserContact implements java.io.Serializable {

	private UserContactId id;
	private UserD userDByUserId;
	private UserD userDByUserContactId;

	public UserContact() {
	}

	public UserContact(UserContactId id, UserD userDByUserId, UserD userDByUserContactId) {
		this.id = id;
		this.userDByUserId = userDByUserId;
		this.userDByUserContactId = userDByUserContactId;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false)),
			@AttributeOverride(name = "userContactId", column = @Column(name = "UserContactId", nullable = false)) })
	public UserContactId getId() {
		return this.id;
	}

	public void setId(UserContactId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false, insertable = false, updatable = false)
	public UserD getUserDByUserId() {
		return this.userDByUserId;
	}

	public void setUserDByUserId(UserD userDByUserId) {
		this.userDByUserId = userDByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserContactId", nullable = false, insertable = false, updatable = false)
	public UserD getUserDByUserContactId() {
		return this.userDByUserContactId;
	}

	public void setUserDByUserContactId(UserD userDByUserContactId) {
		this.userDByUserContactId = userDByUserContactId;
	}

}
