package entities;
// Generated 26 Nov, 2016 2:48:47 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserContactId generated by hbm2java
 */
@Embeddable
public class UserContactId implements java.io.Serializable {

	private int userId;
	private int userContactId;

	public UserContactId() {
	}

	public UserContactId(int userId, int userContactId) {
		this.userId = userId;
		this.userContactId = userContactId;
	}

	@Column(name = "UserId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "UserContactId", nullable = false)
	public int getUserContactId() {
		return this.userContactId;
	}

	public void setUserContactId(int userContactId) {
		this.userContactId = userContactId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserContactId))
			return false;
		UserContactId castOther = (UserContactId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getUserContactId() == castOther.getUserContactId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getUserContactId();
		return result;
	}

}
