package entities;
// Generated 26 Nov, 2016 2:48:47 PM by Hibernate Tools 5.2.0.Beta1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserGroups generated by hbm2java
 */
@Entity
@Table(name = "UserGroups", catalog = "ChatSys")
public class UserGroups implements java.io.Serializable {

	private int groupId;
	private String groupName;
	private String groupOwner;
	private Set<Groupusers> groupuserses = new HashSet<Groupusers>(0);

	public UserGroups() {
	}

	public UserGroups(int groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}

	public UserGroups(int groupId, String groupName, String groupOwner, Set<Groupusers> groupuserses) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupOwner = groupOwner;
		this.groupuserses = groupuserses;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.IDENTITY)
	@Column(name = "GroupId", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GroupName", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GroupOwner")
	public String getGroupOwner() {
		return this.groupOwner;
	}

	public void setGroupOwner(String groupOwner) {
		this.groupOwner = groupOwner;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userGroups")
	public Set<Groupusers> getGroupuserses() {
		return this.groupuserses;
	}

	public void setGroupuserses(Set<Groupusers> groupuserses) {
		this.groupuserses = groupuserses;
	}

}
